feeder: test_feeder
jacket:
  height: 100
  deck_space: 500
  diameter: 10
  length: 50
  mass: 350
  unit_cost: 5e6
num_feeders: 1
plant:
  num_turbines: 20
port:
  monthly_rate: 100000
  name: Test Port
  num_cranes: 1
site:
  depth: 40
  distance: 50
transition_piece:
  deck_space: 250
  mass: 350
  unit_cost: 3e6
turbine: 15MW_generic
wtiv: test_wtiv
install_phases:
    - JacketInstallation


# # Module Specific
# OffshoreSubstationInstallation:
#   feeder: example_heavy_feeder
#   num_feeders: 1
# array_system_design:
#   cables:
#   - XLPE_630mm_33kV
#   - XLPE_400mm_33kV
# export_system_design:
#   cables: XLPE_500mm_132kV
#   percent_added_length: 0.0
# scour_protection_design:
#   cost_per_tonne: 40
#   scour_protection_depth: 1
# # Configured Phases
# design_phases:
# - MonopileDesign
# - ScourProtectionDesign
# - ArraySystemDesign
# - ExportSystemDesign
# - OffshoreSubstationDesign
# install_phases:
#   ArrayCableInstallation: 0
#   ExportCableInstallation: 2000
#   MonopileInstallation: !!python/tuple
#   - ScourProtectionInstallation
#   - 0.5
#   OffshoreSubstationInstallation: 0
#   ScourProtectionInstallation: 0
#   TurbineInstallation: !!python/tuple
#   - MonopileInstallation
#   - 0.1
